### ISSUE TITLE
Difference in Spiking Synapse Behavior on CPU and GPU

### ISSUE THREAD

**Issue by wnourse05** [ANNarchy/ANNarchy#10]
Hello,

Generating the following spiking neuron and synapse results in different behavior on CPU and GPU using CUDA:
```python
from ANNarchy import *
setup(dt=0.01, paradigm="cuda")
SpikingNeuron = Neuron(
    parameters="""
        Cm = 5.0
        Gm = 1.0
        bias = 0.0
        tau = 5.0
        To = 1.0
        m = 1.0
        tau_exc = 1.0
        Esyn = 5.0
    """,
    equations="""
        Cm * dv/dt = -Gm * v + bias + g_exc * (Esyn-v) : init = 0.0
        tau * dT/dt = -T + To + m * v : init = 1.0
        tau_exc * dg_exc/dt = -g_exc
    """,
    spike = "v > T",
    reset = "v = 0"
)
SpikingSynapse = Synapse(
    parameters="""
        Gmax = 0.99
        Esyn = 5.0
    """,
    equations="""""",
    pre_spike="""
        g_target = Gmax : max = Gmax
    """
)
net_s = Network()
pop0_s = Population(geometry=1,neuron=SpikingNeuron)
pop1_s = Population(geometry=1,neuron=SpikingNeuron)
proj_s = Projection(
    pre=pop0_s,
    post=pop1_s,
    target='exc',
    synapse=SpikingSynapse
).connect_one_to_one()
net_s.add([pop0_s,pop1_s,proj_s])
```
The desired behavior has `g_exc` being set to `Gmax` on every spike, and otherwise decaying to 0. At no point should `g_exc` be greater than `Gmax`. During simulation, pop0 has an applied current of 5. The neuron has an adaptive firing threshold, so the firing rate varies over time but the maximum synaptic conductance shouldn't. On CPU, this behavior is correct and the synaptic conductance always jumps to the correct value. On GPU, the behavior appears to be that `g_exc` is incremented by `Gmax`, regardless of the current value. The keyword `max = Gmax` appears to be ignored.

**Comment by hdinkelbach** [comment]
Hello,

indeed the boundary term was ignored in the code generation for CUDA devices. I pushed an update to master which should resolve the issue.

Best,
Helge
