### ISSUE TITLE
report() generates empty table

### ISSUE THREAD

**Issue by JBergelt** [ANNarchy/ANNarchy#13]
report() generates empty table for population without paramters, e.g.:
Aux_Neuron = Neuron(name='Aux_Neuron', equations="""r = sum(exc)""")

![grafik](https://github.com/ANNarchy/ANNarchy/assets/128366707/5c1e1529-ef76-410a-8534-86dd8fbeca00)

**Comment by vitay** [comment]
Fixed in master.
