### ISSUE TITLE
ANN-to-SNN conversion does not work with recent Tensorflow (2.16.1)

### ISSUE THREAD

**Issue by hdinkelbach** [ANNarchy/ANNarchy#17]
Hi,

I just noticed that our current ANN-to-SNN converter appears to work nicely with TensorFlow 2.12, but using 2.16.1 (the current stable release) crashes with a _KeyError_ exception. I took a rough look and saw that the save file structure has been changed compared to previous TensorFlow releases.

Best,
Helge

**Comment by vitay** [comment]
Fixed in 4.8.0.
