### ISSUE TITLE
SpikeSourceArray has no rank

### ISSUE THREAD

**Issue by rLarisch** [ANNarchy/ANNarchy#18]
Hello,
if I want to use a SpikeSourceArray in a custom connectivity as a pre-synaptic population (for example) and want to access the ranks of the pre-population, I got the error that the SpikeSourceArray object did not have a 'rank'.

**Comment by vitay** [comment]
The attribute is called `ranks`, as for regular populations. Note that it is simply defined as: `self.ranks = np.arange(self.size, dtype="int32")`.

**Comment by rLarisch** [comment]
Thank you!
I got confused, because a population view have the .rank (without a s) attribute, what I used very often. But a normal population - object only have .ranks. 
Btw in a population view, you get with .rank and .ranks the same list back. So not sure if the attribute .rank is still needed.

**Comment by vitay** [comment]
Yes, we left .rank for backward compatibility, but .ranks should be used instead

**Comment by rLarisch** [comment]
I had a short talk with Helge about this, and if I understand him correctly, the popView.rank is used, when multpile popViews are added together.
So maybe just change '.rank' to '._rank' and use it only internally in ANNarchy?
