### ISSUE TITLE
Issues with tests due to typo (?) and a wrong import

### ISSUE THREAD

**Issue by penguinpee** [ANNarchy/ANNarchy#21]
While running tests I came across a few issues. It seems some typo or other mishap has crept into the code. Two examples (there are more):

https://github.com/ANNarchy/ANNarchy/blob/4c1a89a9cec4eec086e32a51432a237aa008432c/ANNarchy/core/Projection.py#L666

https://github.com/ANNarchy/ANNarchy/blob/4c1a89a9cec4eec086e32a51432a237aa008432c/ANNarchy/extensions/convolution/Pooling.py#L93

The following import statement needed adjustment as well:

https://github.com/ANNarchy/ANNarchy/blob/4c1a89a9cec4eec086e32a51432a237aa008432c/tests/Common/test_RandomVariables.py#L27

I have a patch ready and can submit a PR fixing those. But I wanted to ask first. Maybe I'm missing something.

**Comment by vitay** [comment]
Thanks a lot! We changed the logging methods in the last version, and apparently left out some bugs. The PR would be very welcome!

**Comment by vitay** [comment]
Great, thanks a lot!
