### ISSUE TITLE
Bug: Reordering of dendrites in connect_with_function

### ISSUE THREAD

**Issue by alexschw** [ANNarchy/ANNarchy#26]
ANNarchy 4.8.0 breaks during compilation when using unordered dendrites. It did not happen in 4.7.3. The error thrown is: 

> python3: .../ANNarchy/include/LILMatrix.hpp:616: void LILMatrix<IT, ST>::update_matrix_variable_row(std::vector<std::vector<VT> >&, IT, std::vector<VT>) [with VT = double; IT = int; ST = int]: Assertion `(values.size() == variable[lil_idx].size())' failed.

The code to replicate is:

```
from ANNarchy import Neuron, Population, Projection, compile, LILConnectivity
from math import exp


def gaussian2dTo4d_v(pre, post):
    sigma_sq = 0.5
    synapses = LILConnectivity()


    for post2 in range(post.geometry[2]):
        for post3 in range(post.geometry[3]):
            values = []
            pre_ranks = []
            for pre0 in range(pre.geometry[0]):
                for pre1 in range(pre.geometry[1]):
                    weight = exp(-(((post2 - pre0)**2 + (post3 - pre1)**2) / sigma_sq))
                    if weight > 0.001:
                        # connect
                        pre_rank = pre.rank_from_coordinates((pre0, pre1))
                        pre_ranks.append(pre_rank)
                        values.append(weight)

            for post0 in range(post.geometry[0]):
                for post1 in range(post.geometry[1]):
                    post_rank = post.rank_from_coordinates((post0, post1, post2, post3))
                    synapses.add(post_rank, pre_ranks, values, [0])
    return synapses


neur = Neuron(parameters="tau = 10.0 : population ", equations="tau * dr/dt + r = sum(inp)")

preLayer = Population(geometry=(21, 17), neuron=neur)
postLayer = Population(geometry=(21, 17, 21, 17), neuron=neur)

conn = Projection(pre=preLayer, post=postLayer, target='inp')
conn.connect_with_func(method=gaussian2dTo4d_v)
compile()
```

**Comment by hdinkelbach** [comment]
I could reproduce the bug using the above script and ANNarchy 4.8.0.4. Running in debug produces the following output:

LILMatrix::LILMatrix() with dense dimensions 127449 times 357
Instantiate C++ objects ...
LILMatrix::init_matrix_from_lil()
Sort the LIL entries by row index ...
  #rows: 127449
  #columns: 357
  #nnz: 1067073
  #empty rows: 0

considering the number of non-zeros (nnz), one cleary sees that, a large fraction of created synapes is not stored correctly. The matrix dimensions appear to be correct and one can see that as Alex mentioned, the row-sorting is applied. 

I will need to take a more in-depth look on the issue later.

**Comment by hdinkelbach** [comment]
As it turns out, the issue was simply that only the column indices has been re-ordered, while the values/delays arrays remained in their original ordering.
