### ISSUE TITLE
Possible bug with asking for Monitor.period attribute

### ISSUE THREAD

**Issue by dionperd** [ANNarchy/ANNarchy#3]
Hello,

I am getting the error 

'ANNarchyCore0.PopRecorder2_wrapper' object has no attribute 'period' 

when asking to read the Monitor.period (as well as perhaps other attributes), 
for all versions of ANNarchy 4.7.++

This comes up via code of tvb_annarchy code, but I don't think that this should be of any importance, given the location of the error:
line 124 of Annarchy/core/Monitor.py:
self.cynstance.period * Global.config['dt'].

**Comment by hdinkelbach** [comment]
Hello,

Thanks for the bug report and indeed, this was a bug in the code generation of the cython wrapper. The period and period_offset attribute were not exported. The above mentioned commit should fix this.

Best,
Helge

**Comment by vitay** [comment]
Fixed in 4.7.1.5.
